### PR TITLE
chromium: new package

### PR DESCRIPTION
**Pull request by paralin**
Unfortunately chromium in Buildroot was never merged:

http://lists.buildroot.org/pipermail/buildroot/2018-July/225782.html
https://github.com/jakogut/buildroot/commits/chromium-v7-wip

Abandoned 2019

However: I have updated the patch series and adjusted it to build against latest
skiff and latest chromium (this PR).

### CODE REVIEW

**Comment by paralin** [comment]
@tianyuanhao can you help me test this by any chance?

**Comment by paralin** [comment]
cc @jakogut

**Comment by tianyuanhao** [comment]
@paralin Can you provide a `defconfig`? I haven't compiled a desktop environment with Buildroot.

**Comment by paralin** [comment]
@tianyuanhao something like this:

```
BR2_x86_64=y
BR2_x86_core_avx2=y
BR2_CCACHE=y
BR2_OPTIMIZE_2=y
BR2_TOOLCHAIN_BUILDROOT_GLIBC=y
BR2_KERNEL_HEADERS_VERSION=y
BR2_DEFAULT_KERNEL_VERSION="5.8.15"
BR2_GCC_VERSION_9_X=y
BR2_TOOLCHAIN_BUILDROOT_CXX=y
BR2_INIT_SYSTEMD=y
BR2_SYSTEM_BIN_SH_BASH=y
BR2_ENABLE_LOCALE_WHITELIST="C en_US en_US.UTF-8"
BR2_GENERATE_LOCALE="en_US.UTF-8"
BR2_PACKAGE_CHROMIUM=y
BR2_PACKAGE_BZIP2=y
BR2_PACKAGE_GZIP=y
BR2_PACKAGE_UNZIP=y
BR2_PACKAGE_XZ=y
BR2_PACKAGE_ZIP=y
BR2_PACKAGE_LSOF=y
BR2_PACKAGE_BINUTILS=y
BR2_PACKAGE_GREP=y
BR2_PACKAGE_E2FSPROGS=y
BR2_PACKAGE_E2FSPROGS_RESIZE2FS=y
BR2_PACKAGE_MMC_UTILS=y
BR2_PACKAGE_MESA3D=y
BR2_PACKAGE_MESA3D_LLVM=y
BR2_PACKAGE_MESA3D_GALLIUM_DRIVER_I915=y
BR2_PACKAGE_MESA3D_GALLIUM_DRIVER_NOUVEAU=y
BR2_PACKAGE_MESA3D_OPENGL_GLX=y
BR2_PACKAGE_MESA3D_OPENGL_EGL=y
BR2_PACKAGE_MESA3D_OPENGL_ES=y
BR2_PACKAGE_XORG7=y
BR2_PACKAGE_XSERVER_XORG_SERVER=y
BR2_PACKAGE_XSERVER_XORG_SERVER_XVFB=y
BR2_PACKAGE_COREUTILS=y
BR2_TARGET_ROOTFS_CPIO=y
BR2_TARGET_ROOTFS_CPIO_GZIP=y

```

**Review by ghost — COMMENTED** [review]
&nbsp;

**Comment by paralin** [comment]
Noted, thanks.

>

**Comment by tianyuanhao** [comment]
@paralin I tried, but I failed. For some reason, I cannot download the Chromium source package. It is too big.

**Comment by paralin** [comment]
@tianyuanhao Hah. Well, the build failed for me. Going to revisit this soon

**Pull request closed without merging**
