### PR TITLE
package/libcap: disable golang for host-libcap

### PR DESCRIPTION
**Pull request by ghost**
See:

https://git.kernel.org/pub/scm/linux/kernel/git/morgan/libcap.git/commit/Make.Rules?id=0615d996379dceedefcd65a114f93fefd81c208f
https://git.pengutronix.de/cgit/ptxdist/commit/?id=a986feb514bd7ff6c75d0fb7a3fc7ea3b0169f44
https://patchwork.ozlabs.org/project/buildroot/patch/1f3d9456-9ca2-75f4-7e15-d851e65005ea@aliyun.com/

May fix:

https://github.com/skiffos/buildroot/runs/1077173332

### CODE REVIEW

**Comment by paralin** [comment]
Thanks for the PR, I'm looking at the failing checks now

**Review by paralin — DISMISSED** [review]
LGTM once CI passes

**Review by paralin — APPROVED** [review]

**Comment by paralin** [comment]
Looks to me like https://github.com/skiffos/buildroot/runs/1089866354?check_suite_focus=true passed, any idea if this is 100% necessary (still)?

**Review by paralin — DISMISSED** [review]
https://github.com/skiffos/buildroot/runs/1089866354?check_suite_focus=true

**Review by paralin — APPROVED** [review]

**Comment by paralin** [comment]
Despite the build passing it's probably still correct to merge this due to the issue reports + mails you linked, and if skiff/next were on upstream/master it might actually still be failing without this patch.

I'm preparing to make "stable" 2020.05.x, "master" 2020.08.x and "next" upstream/master after the next series of releases.

**Comment by tianyuanhao** [comment]
@paralin When go is installed in the compilation environment, or host-go has been compiled before, an error will occur when compiling host-libcap.

The reason why CI passed is that go is not installed in the compilation environment, and host-go is compiled after host-libcap.

**Comment by paralin** [comment]
@tianyuanhao OK - merged, thanks for the PR.

**Pull request merged**
