### PR TITLE
package/balena-engine: new package

### PR DESCRIPTION
**Pull request by ghost**
> balenaEngine is a new container engine purpose-built for embedded and IoT use cases and compatible with Docker containers. Based on Moby Project technology from Docker, balenaEngine supports container deltas for 10-70x more efficient bandwidth usage, has 3.5x smaller binaries, uses RAM and storage more conservatively, and focuses on atomicity and durability of container pulling.

### CODE REVIEW

**Comment by tianyuanhao** [comment]
@paralin Would you like to submit this package to upstream and maintain it? I am not familiar with *Go*.

I try to use `balena-engine` instead of `docker` in an embedded system.

**Comment by tianyuanhao** [comment]
Refer to [balena_git.bb](https://github.com/balena-os/meta-balena/blob/master/meta-balena-common/recipes-containers/balena/balena_git.bb) and [docker-engine.mk](https://github.com/buildroot/buildroot/blob/master/package/docker-engine/docker-engine.mk).

**Comment by tianyuanhao** [comment]
See https://patchwork.ozlabs.org/project/buildroot/patch/651f579d-07ad-afc4-4515-0061016dfc02@savronik.com.tr/

**Comment by paralin** [comment]
Nice, I'll try it out. Interesting.

**Comment by paralin** [comment]
Since this is nearly the same thing as docker-engine, perhaps it would be better to add a "option" multi-select configuration to docker engine for the "moby upstream?" - I.e.

```
# balena-engine fork
BR2_PACKAGE_DOCKER_ENGINE_VARIANT_BALENA=y
```

vs the default

```
# docker community edition
BR2_PACKAGE_DOCKER_ENGINE_VARIANT_CE=y
```

**Comment by tianyuanhao** [comment]
In fact, balena-engine is just compatible with docker containers, but it is not completely consistent with docker. It did a lot of renaming, such as:

- /usr/bin/docker -> /usr/bin/balena-engine
- /usr/bin/dockerd -> /usr/bin/balena-engine-daemon
- /var/run/docker.sock -> /var/run/balena-engine.sock

To seamlessly switch from docker to balena-engine, some symbolic links need to be established.

I suggest not to do this, it is better to let users realize that they are using balena-engine instead of docker.

**Comment by tianyuanhao** [comment]
@robertgzr We are doing something similar to balena-os/balena-engine#80 here. Can you give some suggestions?

I am confused whether the version number of `cli`, `containerd` and `runc` should be the same as `balena-engine`?

**Comment by paralin** [comment]
@tianyuanhao If it's like the upstream docker-engine then they don't need to be version locked together.

**Comment by tianyuanhao** [comment]
Although the files of `docker` and `balena-engine` can coexist and both can run `hello-world` separately, there seems to be some namespace conflicts when running containers to provide network services.

For example, use `docker` and `balena-engine` at the same time to run `portainer` with different port numbers. However, access to these ports points to the same container.

I did not continue to investigate further, but I guess it may be because I only used the fewest kernel options selected by `docker-engine.mk`. Anyway, I suggest adding `depends on !BR2_PACKAGE_DOCKER_ENGINE` to `Config.in`.

**Comment by tianyuanhao** [comment]
By adding a kernel configuration fragment similar to the [docker](https://github.com/skiffos/SkiffOS/blob/master/configs/apps/docker/kernel/docker) file, it seems that `docker` and `balena-engine` can coexist without affecting each other.

This seems to indicate that the kernel configuration in `docker-engine.mk` is not enough.

**Comment by tianyuanhao** [comment]
I updated this patch at tianyuanhao@d16f7d1.

**Comment by paralin** [comment]
Haven't had a chance to test yet, but will be able to soon hopefully

**Comment by paralin** [comment]
@tianyuanhao Annoyingly I can't update the source of this PR, I made a branch on the repo and created #13

**Pull request closed without merging**
